import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  value: "oculon project",
  isSidebarVisible: true,
  section: [
    {
      sectionName: "Inputs",
      group: [
        {
          groupName: "group 1",
          data: [
            {
              column1: "Data 1",
              column2: "Expand",
              column3: "+ Data",
              column4: "f Enter formula",
              column5: [
                "Group 1 Sub-Data 1",
                "Group 1 Sub-Data 2",
                "Group 1 Sub-Data 3",
                "Group 1 Sub-Data 4",
                "Group 1 Sub-Data 5",
                "Group 1 Sub-Data 6",
                "Group 1 Sub-Data 7",
                "Group 1 Sub-Data 8",
                "Group 1 Sub-Data 9",
                "Group 1 Sub-Data 10",
                "Group 1 Sub-Data 11",
                "Group 1 Sub-Data 12",
              ],
            },
            {
              column1: "Data A",
              column2: "Expand",
              column3: "+ Data",
              column4: "f Enter formula",
              column5: [
                "Group 1 Sub-Data A",
                "Group 1 Sub-Data B",
                "Group 1 Sub-Data C",
                "Group 1 Sub-Data D",
                "Group 1 Sub-Data E",
                "Group 1 Sub-Data F",
                "Group 1 Sub-Data G",
                "Group 1 Sub-Data H",
                "Group 1 Sub-Data I",
                "Group 1 Sub-Data J",
                "Group 1 Sub-Data K",
                "Group 1 Sub-Data L",
              ],
            },
          ],
        },
        {
          groupName: "group 2",
          data: [
            {
              column1: "Data 1",
              column2: "Expand",
              column3: "+ Data",
              column4: "f Enter formula",
              column5: [
                "Group 2 Sub-Data 1",
                "Group 2 Sub-Data 2",
                "Group 2 Sub-Data 3",
                "Group 2 Sub-Data 4",
                "Group 2 Sub-Data 5",
                "Group 2 Sub-Data 6",
                "Group 2 Sub-Data 7",
                "Group 2 Sub-Data 8",
                "Group 2 Sub-Data 9",
                "Group 2 Sub-Data 10",
                "Group 2 Sub-Data 11",
                "Group 2 Sub-Data 12",
              ],
            },
            {
              column1: "Data A",
              column2: "Expand",
              column3: "+ Data",
              column4: "f Enter formula",
              column5: [
                "Group 2 Sub-Data A",
                "Group 2 Sub-Data B",
                "Group 2 Sub-Data C",
                "Group 2 Sub-Data D",
                "Group 2 Sub-Data E",
                "Group 2 Sub-Data F",
                "Group 2 Sub-Data G",
                "Group 2 Sub-Data H",
                "Group 2 Sub-Data I",
                "Group 2 Sub-Data J",
                "Group 2 Sub-Data K",
                "Group 2 Sub-Data L",
              ],
            },
          ],
        },
      ],
      data: [
        {
          column1: "Data 1",
          column2: "Expand",
          column3: "+ Data",
          column4: "f Enter formula",
          column5: [
            "Sub-Data 1",
            "Sub-Data 2",
            "Sub-Data 3",
            "Sub-Data 4",
            "Sub-Data 5",
            "Sub-Data 6",
            "Sub-Data 7",
            "Sub-Data 8",
            "Sub-Data 9",
            "Sub-Data 10",
            "Sub-Data 11",
            "Sub-Data 12",
          ],
        },
        {
          column1: "Data A",
          column2: "Expand",
          column3: "+ Data",
          column4: "f Enter formula",
          column5: [
            "Sub-Data A",
            "Sub-Data B",
            "Sub-Data C",
            "Sub-Data D",
            "Sub-Data E",
            "Sub-Data F",
            "Sub-Data G",
            "Sub-Data H",
            "Sub-Data I",
            "Sub-Data J",
            "Sub-Data K",
            "Sub-Data L",
          ],
        },
        {
          column1: "Data X",
          column2: "Expand",
          column3: "+ Data",
          column4: "f Enter formula",
          column5: [
            "Sub-Data X1",
            "Sub-Data X2",
            "Sub-Data X3",
            "Sub-Data X4",
            "Sub-Data X5",
            "Sub-Data X6",
            "Sub-Data X7",
            "Sub-Data X8",
            "Sub-Data X9",
            "Sub-Data X10",
            "Sub-Data X11",
            "Sub-Data X12",
          ],
        },
        {
          column1: "Data P",
          column2: "Expand",
          column3: "+ Data",
          column4: "f Enter formula",
          column5: [
            "Sub-Data P1",
            "Sub-Data P2",
            "Sub-Data P3",
            "Sub-Data P4",
            "Sub-Data P5",
            "Sub-Data P6",
            "Sub-Data P7",
            "Sub-Data P8",
            "Sub-Data P9",
            "Sub-Data P10",
            "Sub-Data P11",
            "Sub-Data P12",
          ],
        },
        {
          column1: "Data T",
          column2: "Expand",
          column3: "+ Data",
          column4: "f Enter formula",
          column5: [
            "Sub-Data T1",
            "Sub-Data T2",
            "Sub-Data T3",
            "Sub-Data T4",
            "Sub-Data T5",
            "Sub-Data T6",
            "Sub-Data T7",
            "Sub-Data T8",
            "Sub-Data T9",
            "Sub-Data T10",
            "Sub-Data T11",
            "Sub-Data T12",
          ],
        },
        {
          column1: "Data M",
          column2: "Expand",
          column3: "+ Data",
          column4: "f Enter formula",
          column5: [
            "Sub-Data M1",
            "Sub-Data M2",
            "Sub-Data M3",
            "Sub-Data M4",
            "Sub-Data M5",
            "Sub-Data M6",
            "Sub-Data M7",
            "Sub-Data M8",
            "Sub-Data M9",
            "Sub-Data M10",
            "Sub-Data M11",
            "Sub-Data M12",
          ],
        },
      ],
    },
    // Additional main object for "Calculations"
    {
      sectionName: "Calculations",
      group: [
        {
          groupName: "group A",
          data: [
            {
              column1: "Calculation 1",
              column2: "Expand",
              column3: "+ Data",
              column4: "f Enter formula",
              column5: [
                "Group A Sub-Calculation 1",
                "Group A Sub-Calculation 2",
                "Group A Sub-Calculation 3",
                "Group A Sub-Calculation 4",
                "Group A Sub-Calculation 5",
                "Group A Sub-Calculation 6",
                "Group A Sub-Calculation 7",
                "Group A Sub-Calculation 8",
                "Group A Sub-Calculation 9",
                "Group A Sub-Calculation 10",
                "Group A Sub-Calculation 11",
                "Group A Sub-Calculation 12",
              ],
            },
            {
              column1: "Calculation A",
              column2: "Expand",
              column3: "+ Data",
              column4: "f Enter formula",
              column5: [
                "Group A Sub-Calculation A",
                "Group A Sub-Calculation B",
                "Group A Sub-Calculation C",
                "Group A Sub-Calculation D",
                "Group A Sub-Calculation E",
                "Group A Sub-Calculation F",
                "Group A Sub-Calculation G",
                "Group A Sub-Calculation H",
                "Group A Sub-Calculation I",
                "Group A Sub-Calculation J",
                "Group A Sub-Calculation K",
                "Group A Sub-Calculation L",
              ],
            },
          ],
        },
        {
          groupName: "group B",
          data: [
            {
              column1: "Calculation 1",
              column2: "Expand",
              column3: "+ Data",
              column4: "f Enter formula",
              column5: [
                "Group B Sub-Calculation 1",
                "Group B Sub-Calculation 2",
                "Group B Sub-Calculation 3",
                "Group B Sub-Calculation 4",
                "Group B Sub-Calculation 5",
                "Group B Sub-Calculation 6",
                "Group B Sub-Calculation 7",
                "Group B Sub-Calculation 8",
                "Group B Sub-Calculation 9",
                "Group B Sub-Calculation 10",
                "Group B Sub-Calculation 11",
                "Group B Sub-Calculation 12",
              ],
            },
            {
              column1: "Calculation A",
              column2: "Expand",
              column3: "+ Data",
              column4: "f Enter formula",
              column5: [
                "Group B Sub-Calculation A",
                "Group B Sub-Calculation B",
                "Group B Sub-Calculation C",
                "Group B Sub-Calculation D",
                "Group B Sub-Calculation E",
                "Group B Sub-Calculation F",
                "Group B Sub-Calculation G",
                "Group B Sub-Calculation H",
                "Group B Sub-Calculation I",
                "Group B Sub-Calculation J",
                "Group B Sub-Calculation K",
                "Group B Sub-Calculation L",
              ],
            },
          ],
        },
      ],
      data: [
        {
          column1: "Calculation 1",
          column2: "Expand",
          column3: "+ Data",
          column4: "f Enter formula",
          column5: [
            "Sub-Calculation 1",
            "Sub-Calculation 2",
            "Sub-Calculation 3",
            "Sub-Calculation 4",
            "Sub-Calculation 5",
            "Sub-Calculation 6",
            "Sub-Calculation 7",
            "Sub-Calculation 8",
            "Sub-Calculation 9",
            "Sub-Calculation 10",
            "Sub-Calculation 11",
            "Sub-Calculation 12",
          ],
        },
        {
          column1: "Calculation A",
          column2: "Expand",
          column3: "+ Data",
          column4: "f Enter formula",
          column5: [
            "Sub-Calculation A",
            "Sub-Calculation B",
            "Sub-Calculation C",
            "Sub-Calculation D",
            "Sub-Calculation E",
            "Sub-Calculation F",
            "Sub-Calculation G",
            "Sub-Calculation H",
            "Sub-Calculation I",
            "Sub-Calculation J",
            "Sub-Calculation K",
            "Sub-Calculation L",
          ],
        },
      ],
    },
  ],
  dateArray: [
    "Jan 2024",
    "Feb 2024",
    "Mar 2024",
    "Apr 2024",
    "May 2024",
    "Jun 2024",
    "Jul 2024",
    "Aug 2024",
    "Sep 2024",
    "Oct 2024",
    "Nov 2024",
    "Dec 2024",
  ],
};

export const spreadSheetSlice = createSlice({
  name: "spreadSheetSlice",
  initialState,
  reducers: {
    demoReducer: (state, action) => {
      state.value = action.payload;
    },
    setIsSidebarVisible: (state, action) => {
      state.isSidebarVisible = action.payload;
    },
    addSectionData: (state) => {
      const sectionDuplicate = [...state.section];
      sectionDuplicate.push({
        sectionName: "Section1",
      });
      state.section = sectionDuplicate;
    },
  },
});
export const { demoReducer, setIsSidebarVisible, addSectionData } =
  spreadSheetSlice.actions;

export default spreadSheetSlice.reducer;
